# Tutorial 2: Introduction to NumPy

In this tutorial, our goal is to become familiar with NumPy, a fundamental library for scientific computing in Python. We'll cover array creation, basic operations, indexing, reshaping, and mathematical functions.

## 1. Installing and Importing NumPy

NumPy is the foundation of scientific computing in Python. First, we need to import it:

- **Import NumPy**: `import numpy as np`
- NumPy is typically abbreviated as `np` for convenience
- If not installed, use: `pip install numpy`

In [ ]:
# Import NumPy
import numpy as np

# Check NumPy version
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


In [ ]:
# !pip install numpy

## 2. Creating NumPy Arrays

NumPy arrays are the core data structure. You can create them in several ways:

1. **From lists**: `np.array([1, 2, 3])`
2. **Zeros**: `np.zeros(shape)`
3. **Ones**: `np.ones(shape)`
4. **Range**: `np.arange(start, stop, step)`
5. **Linspace**: `np.linspace(start, stop, num)`
6. **Random**: `np.random.random(shape)`

In [ ]:
# Create array from list
arr_from_list = np.array([1, 2, 3])
print("Array from list:", arr_from_list, type(arr_from_list))

Array from list: [1 2 3] <class 'numpy.ndarray'>


In [ ]:
# Create 2D array from nested lists
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:")
print(arr_2d)


2D array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Create array of zeros
zeros_arr = np.zeros(5)
print("\nZeros array:", zeros_arr)

# Create array of ones
ones_arr = np.ones((2, 3))
print("\nOnes array (2x3):")
print(ones_arr)


Zeros array: [0. 0. 0. 0. 0.]

Ones array (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Create array using arange
range_arr = np.arange(0, 10, 2)
print("\nRange array (0 to 10, step 2):", range_arr)


Range array (0 to 10, step 2): [0 2 4 6 8]


In [ ]:
# Create array using linspace
# linear
linspace_arr = np.linspace(0, 1, 5)
print("\nLinspace array (0 to 1, 5 points):", linspace_arr)


Linspace array (0 to 1, 5 points): [0.   0.25 0.5  0.75 1.  ]


## 3. Array Properties and Basic Operations

Arrays have important properties and support basic operations:

- **Shape**: `.shape` (dimensions)
- **Size**: `.size` (total number of elements)
- **Data type**: `.dtype` (type of elements)
- **Dimensions**: `.ndim` (number of dimensions)
- **Element operations**: `+`, `-`, `*`, `/`, `**` (applied element-wise)

In [ ]:
# Using the 2D array from previous example
arr = arr_2d
print("Array:")
print(arr)

# Array properties
print("\n Array properties:")
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Data type: ", arr.dtype)
print("Dimensions:", arr.ndim)

Array:
[[1 2 3]
 [4 5 6]]

 Array properties:
Shape:  (2, 3)
Size:  6
Data type:  int64
Dimensions: 2


In [ ]:
# Element-wise operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("\nElement-wise operations:")
print("arr1:", arr1)
print("arr2:", arr2)

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)


Element-wise operations:
arr1: [1 2 3]
arr2: [4 5 6]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [ ]:
# Scalar operations
print("\nScalar operations:")
print("Power:", arr1 ** 2)
print("arr1 + 5:", arr1 + 5)
print("arr1 * 3:", arr1 * 3)


Scalar operations:
Power: [1 4 9]
arr1 + 5: [6 7 8]
arr1 * 3: [3 6 9]


## 4. Array Indexing and Slicing

Access specific elements, rows, or columns from arrays:

- **1D indexing**: `arr[index]`
- **2D indexing**: `arr[row, col]` or `arr[row][col]`
- **Slicing**: `arr[start:end:step]`
- **2D slicing**: `arr[row_start:row_end, col_start:col_end]`
- **Boolean indexing**: `arr[arr > value]`

In [ ]:
# Create sample arrays
arr_1d = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("1D array:", arr_1d)
print("2D array:")
print(arr_2d)

1D array: [10 20 30 40 50]
2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 1D indexing
print("\n1D indexing:")
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])
print("Elements 1-3:", arr_1d[1:4])


1D indexing:
First element: 10
Last element: 50
Elements 1-3: [20 30 40]


In [ ]:
# 2D indexing
print("\n2D indexing:")
print("Element at (0, 2):", arr_2d[0, 2])  # compared to list indexing: ls[0][2]
print("Element at (1, 1):", arr_2d[1, 1])

In [ ]:
# Slicing rows and columns
print("\nSlicing:")
print("First row:", arr_2d[0, :])
print("Second column:", arr_2d[:, 1])

print("First 2 rows, first 3 columns:")


Slicing:
First row: [1 2 3 4]
Second column: [ 2  6 10]
First 2 rows, first 3 columns:


In [ ]:
# Boolean indexing
print("\nBoolean indexing:")
print("Elements > 30 in 1D array:", arr_1d[arr_1d > 30])
print("Elements > 6 in 2D array:", arr_2d[arr_2d > 6])


Boolean indexing:
Elements > 30 in 1D array: [40 50]
Elements > 6 in 2D array: [ 7  8  9 10 11 12]


In [ ]:
arr_1d > 30

array([False, False, False,  True,  True])

## 5. Reshaping and Manipulating Arrays

Change the shape and structure of arrays:

- **Reshape**: `arr.reshape(new_shape)`
- **Flatten**: `arr.flatten()` or `arr.ravel()`
- **Transpose**: `arr.T` or `arr.transpose()`
- **Concatenate**: `np.concatenate([arr1, arr2])`
- **Stack**: `np.vstack([arr1, arr2])`, `np.hstack([arr1, arr2])`
- **Split**: `np.split(arr, sections)`

In [ ]:
# Create sample array
arr = np.arange(12)
print("Original array:", arr)
print("Shape:", arr.shape)

# Reshape
reshaped = arr.reshape(3, 4)
print("\nReshaped (3x4):")
print(reshaped)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Reshape to different dimensions
reshaped_2 = arr.reshape(2, 6)
print("\nReshaped (2x6):")
print(reshaped_2)



Reshaped (2x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# Flatten
flattened = reshaped_2.flatten()
print("\nFlattened:", flattened)

# Transpose
transposed = reshaped_2.T
transposed = reshaped_2.transpose()
print("\nTranspose of reshaped:")
print(transposed)


Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose of reshaped:
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [ ]:
# Concatenate arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate([arr1, arr2])
print("\nConcatenated:", concatenated)


Concatenated: [1 2 3 4 5 6]


In [ ]:
# Vertical and horizontal stacking
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

vstack_result = np.vstack([matrix1, matrix2])  # np.concatenate(a, b, axis=0)
hstack_result = np.hstack([matrix1, matrix2])  # np.concatenate(a, b, axis=1)

print("\nVertical stack:")
print(vstack_result)
print("\nHorizontal stack:")
print(hstack_result)


Vertical stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack:
[[1 2 5 6]
 [3 4 7 8]]


## 6. Mathematical Functions and Operations

NumPy provides many mathematical functions:

- **Basic math**: `np.sqrt()`, `np.exp()`, `np.log()`, `np.sin()`, `np.cos()`
- **Statistics**: `np.mean()`, `np.median()`, `np.std()`, `np.var()`
- **Aggregation**: `np.sum()`, `np.min()`, `np.max()`, `np.argmin()`, `np.argmax()`
- **Linear algebra**: `np.dot()`, `np.linalg.norm()`, `np.linalg.eig()`

In [ ]:
# Create sample data
data = np.array([1, 4, 9, 16, 25])
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print("Data:", data)
print("Angles:", angles)

Data: [ 1  4  9 16 25]
Angles: [0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [ ]:
# Basic mathematical functions
print("\nBasic math functions:")
print("Square root:", np.sqrt(data))
print("Exponential:", np.exp([1, 2, 3]))
print("Natural log:", np.log([1, 2.718, 7.389]))
print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))


Basic math functions:
Square root: [1. 2. 3. 4. 5.]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural log: [0.         0.99989632 1.99999241]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [ ]:
# Statistical functions
random_data = np.random.normal(10, 2, 20)  # mean=10, std=2, 20 samples
print("\nRandom data (first 10):", random_data[:10])
print("\nStatistical functions:")
print("Mean: ", np.mean(random_data))
print("STD: ", np.std(random_data))
print("Median:", np.median(random_data))
print("VAR:", np.var(random_data))


Random data (first 10): [ 8.36359577  9.71583977  4.71551953  7.89967783  9.80112962 13.53460424
 11.08607545  8.92166162 11.39296753  9.51248042]

Statistical functions:
Mean:  9.863788260992006
STD:  1.9610426943803467
Median: 9.805908132019873
VAR: 3.84568844918253


In [ ]:
# Aggregation functions
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatrix:")
print(matrix)
print("\nAggregation functions:")
print("Sum:", np.sum(matrix))
print("Sum along axis 0 (columns):", np.sum(matrix, axis=0))
print("Sum along axis 1 (rows):", np.sum(matrix, axis=1))
print("Max:", np.max(matrix))
print("Min:", np.min(matrix))
print("Min:", np.min(matrix, axis=0))


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Aggregation functions:
Sum: 45
Sum along axis 0 (columns): [12 15 18]
Sum along axis 1 (rows): [ 6 15 24]
Max: 9
Min: 1
Min: [1 2 3]


In [ ]:
# Linear algebra
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("\nMatrix multiplication:")
print("A:"), print(a)
print("B:"), print(b)
print("A @ B:"), print(a @ b)  # or np.dot(a, b)


Matrix multiplication:
A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
A @ B:
[[19 22]
 [43 50]]


(None, None)

## 7. Broadcasting and Vectorization

NumPy can operate on arrays of different shapes through broadcasting:

- **Broadcasting**: Automatic expansion of smaller arrays to match larger ones
- **Vectorization**: Applying operations to entire arrays without explicit loops
- **Performance**: Much faster than Python loops

Broadcasting rules:
1. Arrays are aligned from the rightmost dimension
2. Dimensions of size 1 can be stretched
3. Missing dimensions are assumed to be size 1

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Original array:")
print(arr)

Original array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Broadcasting with 1D array
row_vector = np.array([10, 20, 30])
print("\nAdding row vector [10, 20, 30]:")
print(arr + row_vector)


Adding row vector [10, 20, 30]:
[[11 22 33]
 [14 25 36]]


In [ ]:
# Broadcasting with column vector
col_vector = np.array([[100], [200]])
print("\nAdding column vector [[100], [200]]:")
print(arr + col_vector)


Adding column vector [[100], [200]]:
[[101 102 103]
 [204 205 206]]


### **Broadcasting Examples**

| Shape 1   | Shape 2   | Resulting Shape | Broadcasting? | Example                 |
|-----------|-----------|-----------------|---------------|-------------------------|
| (3, 1)    | (1, 4)    | (3, 4)          | Yes           | Matrix + Row Vector     |
| (5, 4, 3) | (1, 3)    | (5, 4, 3)       | Yes           | 3D + 2D (last axes)     |
| (2, 3)    | (3,)      | (2, 3)          | Yes           | 2D + 1D (row vector)    |
| (2, 3)    | (2, 1)    | (2, 3)          | Yes           | 2D + 2D (col vector)    |
| (2, 3)    | (2, 2)    | Error           | No            | Incompatible shapes     |

In [ ]:
# (3, 1) and (1, 4) → (3, 4)

# Step 1. Align shapes to the right
## A: (3, 1)
## B: (1, 4)

# Step 2. Compare dimensions
## Last dimension: 1 (A) vs 4 (B) → 1 can be broadcast to 4.
## Second-to-last: 3 (A) vs 1 (B) → 1 can be broadcast to 3.
## Resulting shape: (3, 4)

# Step 3. Broadcasting

A = np.array([[1], [2], [3]])       # Shape (3,1)
B = np.array([[10, 20, 30, 40]])    # Shape (1,4)
C = A + B                           # Shape (3,4)
print(C)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [ ]:
# (5, 4, 3) and (1, 3) → (5, 4, 3)

# Step 1. Align shapes to the right
## A: (5, 4, 3)
## B:    (1, 3) → (1, 1, 3)

# Step 2. Compare dimensions
## Last: 3 vs 3 → match.
## Middle: 4 vs 1 → 1 can be broadcast to 4.
## First: 5 vs 1 → 1 can be broadcast to 5.
## Resulting shape: (5, 4, 3)

# Step 3. Broadcasting

A = np.zeros((5,4,3))
B = np.arange(3).reshape(1,3)
C = A + B  # Shape (5,4,3)

In [ ]:
# Vectorization example - compare with loops
import time

# Large array for performance comparison
large_arr = np.random.random(1000000)

# Using vectorization
start_time = time.time()
result_vectorized = large_arr ** 2 + 2 * large_arr + 1
vectorized_time = time.time() - start_time

# Using Python loop (much slower)
start_time = time.time()
result_loop = []
for x in large_arr:
    result_loop.append(x**2 + 2*x + 1)
loop_time = time.time() - start_time

print(f"\nPerformance comparison:")
print(f"Vectorized time: {vectorized_time:.6f} seconds")
print(f"Loop time: {loop_time:.6f} seconds")
print(f"Speedup: {loop_time/vectorized_time:.1f}x faster")


Performance comparison:
Vectorized time: 0.016078 seconds
Loop time: 0.983266 seconds
Speedup: 61.2x faster


## 8. Short Practices
Try these exercises to reinforce your understanding of NumPy:

1. **Matrix operations**
   - Create a 4x4 matrix with values from 1 to 16
   - Calculate the sum of each row and each column
   - Find elements greater than 10
   - Replace all even numbers with 0

2. **Statistical analysis**
   - Generate 1000 random numbers from a normal distribution (mean=50, std=15)
   - Calculate mean, median, standard deviation
   - Count how many values are above the mean
   - Create a boolean mask for values between 40 and 60

3. **Array manipulation challenge**
   - Create two 3x3 matrices with random values
   - Perform matrix multiplication
   - Reshape the result to a 1D array
   - Sort the array in descending order

In [ ]:
# Exercise 1: Matrix operations
#   Create a 4x4 matrix with values from 1 to 16
#   Calculate the sum of each row and each column
#   Find elements greater than 10
#   Replace all even numbers with 0

#   Create a 4x4 matrix with values from 1 to 16
matrix = np.arange(1, 17).reshape(4, 4)

#   Calculate the sum of each row and each column
row_sums = np.sum(matrix, axis = 1)
col_sums = np.sum(matrix, axis = 0)
print(row_sums)
print(col_sums)

#   Find elements greater than 10
greater_than_10 = matrix[matrix > 10]

#   Replace all even numbers with 0
matrix_copy = matrix.copy()
matrix_copy[matrix_copy % 2 == 0] = 0

In [ ]:
# Exercise 2: Statistical analysis
#   Generate 1000 random numbers from a normal distribution (mean=50, std=15)
#   Calculate mean, median, standard deviation
#   Count how many values are above the mean
#   Create a boolean mask for values between 40 and 60

#   Generate 1000 random numbers from a normal distribution (mean=50, std=15)
random_data = np.random.normal(50, 15, 1000)

#   Calculate mean, median, standard deviation
print(random_data.mean(), random_data.median(), random_data.std())

#   Count how many values are above the mean
above_mean = random_data > random_data.mean()
num_above_mean = above_mean.sum()

#   Create a boolean mask for values between 40 and 60
mask = (random_data > 40) & (random_data < 60)  # & -> AND

In [ ]:
# Exercise 3: Array manipulation challenge
#   Create two 3x3 matrices with random values
#   Perform matrix multiplication
#   Reshape the result to a 1D array
#   Sort the array in descending order

#   Create two 3x3 matrices with random values
A = np.random.random(3, 3)
B = np.random.random(3, 3)

#   Perform matrix multiplication
result = A.dot(B)  # A @ B

#   Reshape the result to a 1D array
result_reshaped = result.reshape(-1)  # flatten


#   Sort the array in descending order
sorted_desc = np.sort(result_reshaped)[::-1]

In [ ]:
A = np.random.random(16)

A_reshape = A.reshape(2, -1)